import { Deal } from "@/types/deals.types";

export const MOCK_DEALS: Deal[] = [
  {
    id: '1',
    title: 'iPhone 13 Pro',
    description: 'Refurbished iPhone 13 Pro in excellent condition',
    price: 799,
    discountPercentage: 15,
    refurbedScore: 95,
    isInSpotlight: true,
  },
  {
    id: '2',
    title: 'MacBook Air M2',
    description: 'Like-new MacBook Air with M2 chip',
    price: 1099,
    discountPercentage: 20,
    refurbedScore: 88,
    isInSpotlight: false,
  },
  {
    id: '3',
    title: 'iPad Pro 11"',
    description: 'Refurbished iPad Pro with Apple Pencil support',
    price: 649,
    refurbedScore: 72,
    isInSpotlight: true,
  },
  {
    id: '4',
    title: 'Samsung Galaxy S23',
    description: 'Premium refurbished Samsung flagship',
    price: 699,
    discountPercentage: 25,
    refurbedScore: 91,
    isInSpotlight: true,
  },
  {
    id: '5',
    title: 'AirPods Pro 2',
    description: 'Certified refurbished with active noise cancellation',
    price: 199,
    refurbedScore: 67,
    isInSpotlight: false,
  },
  {
    id: '6',
    title: 'Apple Watch Series 8',
    description: 'Refurbished smartwatch with health tracking',
    price: 349,
    discountPercentage: 10,
    refurbedScore: 83,
    isInSpotlight: false,
  },
  {
    id: '7',
    title: 'Dell XPS 15',
    description: 'High-performance laptop for professionals',
    price: 1299,
    refurbedScore: 45,
    isInSpotlight: false,
  },
  {
    id: '8',
    title: 'Sony WH-1000XM5',
    description: 'Premium noise-cancelling headphones',
    price: 329,
    discountPercentage: 18,
    refurbedScore: 78,
    isInSpotlight: true,
  },
  {
    id: '9',
    title: 'Google Pixel 7 Pro',
    description: 'Refurbished Google flagship with amazing camera',
    price: 599,
    refurbedScore: 56,
    isInSpotlight: false,
  },
  {
    id: '10',
    title: 'Nintendo Switch OLED',
    description: 'Gaming console in pristine condition',
    price: 299,
    discountPercentage: 12,
    refurbedScore: 100,
    isInSpotlight: true,
  },
];

